### PR TITLE
Add code block to enable Gorilla scheduled task

### PR DESCRIPTION
**Pull request by danhutchings**
SUMMARY:
The current cpe_gorilla resource does not re-enable the `gorilla` scheduled task in the unfortunate scenario the task is disabled. This diff aims to correct that by adding a block to enable/re-enable the scheduled task if it is detected as disabled. The changes were tested via local `chef-client` run.

TEST PLAN:
1. Disable Gorilla scheduled task
2. Run cpe_gorilla resource/cookbook/recipe(s()
3. Validate the scheduled task is not re-enabled
4. Download this diff
5. Run `chef-client` in local mode
6. Validate that the scheduled task is re-enabled

### CODE REVIEW

**Comment by ChefAustin** [comment]
This seems reasonable to me. I am kind of surprised that Chef's `windows_task` resource doesn't inherently check enabled/disabled status with the `:create` action.

I've asked my teammates to take a look to get one more set of eyes on this before we approve/merge.

Thanks for contributing!

**Comment by danhutchings** [comment]
@ChefAustin thank you for the consideration! I was astonished by the same thing. Perhaps that will be a future improvement of the `windows_task` resource. Until then, I appreciate your diligence.

**Comment by arthagopian** [comment]
@danhutchings , thanks for this.  @ChefAustin looks good to me.

**Comment by danhutchings** [comment]
@gleason86 I have made the changes you suggested. Sorry for the strange over commits. I mistakenly commit as a different author on my local branch and was trying to correct it. Let me know if there are any other changes I need to make.

Thanks!

**Review by ChefAustin — APPROVED** [review]

**Pull request merged**
